name: DESCAM-BUILD

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
        node: [1]
    steps:
    - uses: actions/checkout@v1
    - name: unzip
      run: sh install/install_unzip.sh
    - name: systemc
      run: sh install/install_systemc.sh
    - name: gtest
      run: sh install/install_gtest.sh
    - name: z3
      run: sh install/install_z3.sh
    - name: move files
      run: sh install/install_move.sh
    - name: descam
      run: sh install/install_descam.sh
    - name: run_tests
      run: sh install/install_run_tests.sh
    - name: clang
      run: sh install/install_clang.sh
    - name: cleanup
      run: sh install/install_cleanup.sh





